### PR TITLE
Console errors

### LINKED ISSUE #85: Remove the console errors on  login
**Describe the bug**
console errors on login
Screenshot from 2019-05-22 17-36-47

**Additional context**
Are you working on this?
Yes

### PR DESCRIPTION
**Pull request by ritwizsinha**
Fixes #85 

Changes: Removed the console errors caused due to wrong use of  form input and duplicate key  in navbar.js

Surge Deployment Link: https://pr-92-sahaayak.surge.sh

Screenshots for the change: 
Screenshot from 2019-05-23 13-52-57

No console errors

### CODE REVIEW

File: src/components/LoginModal/LoginModal.js [hunk 1]
```diff
@@ -117,10 +101,6 @@ class LoginModal extends Component {
               rules: [{ required: true, message: 'Please input your email!' }],
             })(
               <Input
-                type="email"
```
Comment (harsh-jindal) [inline src/components/LoginModal/LoginModal.js:120]: @ritwizsinha  Add this line `type="email"` . Rest is good 👍

Comment (ritwizsinha) [reply src/components/LoginModal/LoginModal.js:120]: doing

**Review by harsh-jindal — APPROVED** [review]
