### PR TITLE
Issue#90

### LINKED ISSUE #90: Fix the UI of List your vendor page
**Describe the bug**
Currently the page doesn't show a success alert on successfully registering the business. 
"Enter your details" button should be renamed to "List your business" and button color should be primary not error.
Change the hardcoded country code to select dropdown showing each countries name an code beside it. 

**To Reproduce**
1. Go to 'List your business'.
3. Try registering a business.

**Expected behavior**
All the above points shall be fixed.
**Screenshots**
Screenshot 2019-05-23 at 1 02 44 PM

**Additional context**
@ritwizsinha Take this up.

### PR DESCRIPTION
**Pull request by ritwizsinha**
Fixes #90 

Changes: 
1.Changed the color of button to primary 
2.Changed the button text to register your business
3. Showed the registration successful message

Surge Deployment Link: https://pr-93-sahaayak.surge.sh

### CODE REVIEW

File: src/components/VendorSalesPage/VendorSalesPage.js [hunk 1]
```diff
@@ -83,17 +84,230 @@ class VendorSalesPage extends Component {
...
       const prefixSelector = getFieldDecorator('prefix', {
-        initialValue: '86',
+        initialValue: '213',
       })(
-        <Select style={{ width: 70 }}>
-          <Option value="86">+86</Option>
-          <Option value="87">+87</Option>
-        </Select>
+        <Select>
+    <Option data-countryCode="DZ" value="213">Algeria (+213)</Option>
```
Comment (harsh-jindal) [inline src/components/VendorSalesPage/VendorSalesPage.js]: @ritwizsinha Create an array then add these option using a forEach loop

File: src/redux/reducers/vendorReducer.js [hunk 2]
```diff
@@ -1,17 +1,15 @@
 import { REGISTER_BUSINESS_SUCCESS } from '../actions/type';
 
 const initialState = {
-  status: null,
-  msg: ''
+  registrationDone: false
```
Comment (harsh-jindal) [inline src/redux/reducers/vendorReducer.js]: @ritwizsinha This is not right method, server is returning status. Use that. 
Only on success the server is not returning a status code otherwise server is always responding with a status code.

File: src/components/VendorSalesPage/VendorSalesPage.js [hunk 3]
```diff
@@ -83,17 +84,230 @@ class VendorSalesPage extends Component {
...
+		<Option data-countryCode="YE" value="967">Yemen (South)(+967)</Option>
+		<Option data-countryCode="ZM" value="260">Zambia (+260)</Option>
+		<Option data-countryCode="ZW" value="263">Zimbabwe (+263)</Option>
+    </Select>
       );
 
       return (
         <Fragment>
-               {msg ? <Alert message={msg} type="error" /> : null}
+							 {msg ? <Alert message={msg} type={alertType} /> : null}
```
Comment (harsh-jindal) [inline src/components/VendorSalesPage/VendorSalesPage.js]: @ritwizsinha What is this use of alertType ? You are only keeping it empty or error.

**Review by harsh-jindal — CHANGES_REQUESTED** [review]

File: src/components/VendorSalesPage/VendorSalesPage.js (hunk 3 above)
Comment (ritwizsinha) [reply src/components/VendorSalesPage/VendorSalesPage.js]: done

File: src/components/VendorSalesPage/VendorSalesPage.js (hunk 1 above)
Comment (ritwizsinha) [reply src/components/VendorSalesPage/VendorSalesPage.js]: done

**Review by harsh-jindal — APPROVED** [review]
