### PR TITLE
Blank screen is encountered if no service exists

### LINKED ISSUE #134: Blank screen is encountered if no service exists for a particular category
**Describe the bug**
sasa

It should display no service.

**Additional context**
Are you working on this?
Yes

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Fixes #134 

Changes: [Add here what changes you made in this Pull Request and if possible provide links depicting the changes.]

Surge Deployment Link: https://pr-135-sahaayak.surge.sh

Screenshots for the change: [Add here screenshots showing the changes.]
noser

### CODE REVIEW

File: src/components/CategoryWiseServices/CategoryWiseServices.js [hunk 1]
```diff
@@ -44,56 +44,62 @@ class CategoryWiseServices extends Component {
...
-        })
-        ) : (
-                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
-                    <Spin tip="Loading..." size="large" ></Spin>
-                </div>
-            )
+
+        const serviceList = !this.props.categoryService.pending ? 
+        
+            this.props.categoryService.services.length ?
```
Comment (harsh-jindal) [inline src/components/CategoryWiseServices/CategoryWiseServices.js]: @ashwaniYDV This isn't a good method. Don't change this part. Rather check the length of serviceList below and display the message

**Review by harsh-jindal — CHANGES_REQUESTED** [review]

File: src/components/CategoryWiseServices/CategoryWiseServices.js [hunk 2]
```diff
@@ -90,16 +90,16 @@ class CategoryWiseServices extends Component {
             )
         })
         ) : (
-                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
+                [<div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
```
Comment (harsh-jindal) [inline src/components/CategoryWiseServices/CategoryWiseServices.js:93]: Why have you put the div inside `[]` ?

**Review by harsh-jindal — APPROVED** [review]
